# Generated by Django 2.2.6 on 2019-11-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('part', models.CharField(db_column='部门', max_length=10)),
            ],
            options={
                'db_table': '部门',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(db_column='批号', max_length=30)),
                ('extruder_skin', models.IntegerField(db_column='表面判定')),
                ('perf', models.CharField(db_column='性能判定', max_length=4)),
                ('rosh', models.IntegerField(db_column='RoSH')),
                ('density', models.FloatField(db_column='密度')),
                ('lsqd', models.FloatField(db_column='拉伸强度')),
                ('dlscl', models.FloatField(db_column='断裂伸长率')),
                ('dcwd', models.IntegerField(db_column='低冲温度')),
                ('dlgs', models.IntegerField(db_column='断裂根数')),
                ('tjdzlwd', models.IntegerField(db_column='体积电阻率温度')),
                ('tjdzl', models.BigIntegerField(db_column='体积电阻率')),
                ('ydbz', models.CharField(db_column='硬度标准', max_length=2)),
                ('yd', models.FloatField(db_column='硬度')),
                ('time200c', models.IntegerField(db_column='200℃热稳定时间')),
                ('jdqd', models.IntegerField(db_column='介电强度')),
                ('yzs', models.FloatField(db_column='氧指数')),
                ('rrzs', models.FloatField(db_column='熔融指数')),
                ('kssfcd', models.FloatField(db_column='快速水分测定')),
                ('rbxwd', models.CharField(db_column='热变形温度', max_length=3)),
                ('rbx', models.FloatField(db_column='热变形')),
            ],
            options={
                'db_table': '常规性能',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProInfo',
            fields=[
                ('batch', models.CharField(db_column='批号', max_length=30, primary_key=True, serialize=False)),
                ('customer', models.CharField(db_column='客户', max_length=30)),
                ('pro_type', models.CharField(db_column='产品型号', max_length=30)),
                ('pro_color', models.CharField(db_column='颜色', max_length=10)),
                ('pro_date', models.DateField(db_column='生产日期')),
                ('test_date', models.DateField(db_column='检验日期')),
            ],
            options={
                'db_table': '产品信息',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnPass',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('up_type', models.CharField(db_column='不良品种类', max_length=10)),
                ('customer', models.CharField(db_column='客户', max_length=30)),
                ('up_name', models.CharField(db_column='不良品名称', max_length=30)),
                ('batch', models.CharField(db_column='批号', max_length=20)),
                ('pro_date', models.DateField(db_column='生产日期')),
                ('pro_qty', models.FloatField(db_column='数量Kg')),
                ('up_desc', models.TextField(db_column='不合格描述')),
                ('result_ana', models.TextField(db_column='原因分析')),
                ('correct_act', models.TextField(db_column='纠正措施')),
                ('pre_act', models.TextField(db_column='预防措施')),
                ('tech_idea', models.TextField(db_column='技术部意见')),
                ('process_idea', models.TextField(db_column='工艺部意见')),
                ('qa_idea', models.TextField(db_column='质量部意见')),
                ('serv_idea', models.TextField(db_column='技术支持部意见')),
            ],
            options={
                'db_table': '不合格品登记',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpStatus',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('caseto_by_qa', models.CharField(db_column='caseto_by_QA', max_length=10)),
                ('case_closed_flag', models.IntegerField(db_column='case_closed_flag')),
            ],
            options={
                'db_table': '状态标记',
                'managed': False,
            },
        ),
    ]
