# Generated by Django 2.2.6 on 2019-11-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dw_query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JokeUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
    ]
