# Generated by Django 2.2.6 on 2019-11-11 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dw_query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('to_part', models.CharField(max_length=10)),
                ('sugg_act', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='files/topics/%Y%m%d')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/topics/%Y%m%d')),
                ('unpass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dw_query.UnPass')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('from_part', models.CharField(max_length=10)),
                ('act', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.AuditTopic')),
            ],
        ),
    ]
