# Generated by Django 2.2.6 on 2019-12-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.CharField(max_length=10)),
                ('to_part', models.CharField(max_length=10)),
                ('sugg_act', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='files/topics/%Y%m%d')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/topics/%Y%m%d')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('from_part', models.CharField(max_length=10)),
                ('act', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='files/entries/%Y%m%d')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/entries/%Y%m%d')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
